FROM mongo:latest

# Copy the initialization script into the container
ENV MONGO_INITDB_ROOT_USERNAME=alfiya
ENV MONGO_INITDB_ROOT_PASSWORD=alfiya
ENV MONGO_INITDB_DATABASE=mydb
COPY init-db.js /docker-entrypoint-initdb.d/
RUN chmod +x /docker-entrypoint-initdb.d/init-db.js
# Expose the default MongoDB port
EXPOSE 27017

# Run MongoDB when the container starts
CMD ["mongod"]

